[package]
name = "radare2-sys"
version = "0.1.0"
authors = ["Petros Angelatos <petrosagg@gmail.com>"]
edition = "2018"
description = "bindings to radare2's C libraries"
license = "MIT"

[dependencies]

[build-dependencies]
bindgen = "0.51"
